
variables:
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: ${DB_DATABASE}
  DB_PORT: ${DB_PORT}

image: docker/compose

services:
  - docker:dind

stages:
  - test

phpunit-test:
  stage: test
  script:
    - docker-compose build
    - docker-compose up -d
    - docker exec php-collab composer install
    - docker exec php-collab php artisan migrate
    - docker exec php-collab php artisan db:seed
    - cd site && vendor/bin/phpunit --coverage-text --colors=never