image: docker

stages:
  - test

phpunit-test:
  stage: test
  script:
    - docker-compose build
    - docker-compose up -d
    - docker exec php-collab composer install
    - docker exec php-collab php artisan migrate
    - docker exec php-collab php artisan db:seed
    - cd site && vendor/bin/phpunit --coverage-text --colors=never