version: '3'
services:
    php:
        container_name: php-collab
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./site:/site/
        ports:
            - 8080:80
        networks:
            - database
        depends_on:
            - db
        env_file:
            - .env
    db:
        container_name: db-collab
        image: mariadb:10.6.4
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3307:${DB_PORT}
        networks:
            - database
    phpmyadmin:
        container_name: phpmyadmin-collab
        image: phpmyadmin/phpmyadmin:5.1.1
        depends_on:
            - db
        ports:
            - 3333:80
        environment:
            - PMA_HOST=db:${DB_PORT}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        networks:
            - database
volumes:
    mysqldata: {} 
networks:
    database: