#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

modified_files=`git diff --cached --name-only --diff-filter=ACM`
input_file=$1
for file in $modified_files
do
    if [ "$file" != ".husky/pre-commit" ]; then
        if grep -q "print_r" $file || grep -q "var_dump" $file
            then
            echo "Found a print_r or a var_dump in $file, can't commit while still here"
            exit 1
        fi
    fi
done
while read -r line; do
  len=${#line}
  if [ "$len" -ge 140 ]
    then
      echo "Can't have a line in commit-msg having more than 140 chars"
      exit 1
    fi
done < "$input_file"
exit 0